// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axudniivspjmjrtzqynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dWRuaWl2c3BqbWpydHpxeW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMzk2ODUsImV4cCI6MjEwNDYxNTY4NX0.nwvhBZ5LG777K7Lwef-cuvY73dB7tRlXXiO-5iq_KYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});