/**
 * CDN-hosted photographs of Satyabhama Majhi's artworks, projects and portrait.
 * Each pointer file is generated by the assets pipeline; only `.url` is used.
 */
import artistPortrait from "@/assets/photos/artist-portrait.jpg.asset.json";
import cityMapBlue from "@/assets/photos/city-map-blue.jpg.asset.json";
import cityRedMarket from "@/assets/photos/city-red-market.jpg.asset.json";
import dongariaPortrait from "@/assets/photos/dongaria-portrait.jpg.asset.json";
import groveGathering from "@/assets/photos/grove-gathering.jpg.asset.json";
import hillProcession from "@/assets/photos/hill-procession.jpg.asset.json";
import hunger from "@/assets/photos/hunger.jpg.asset.json";
import marketAbundance from "@/assets/photos/market-abundance.jpg.asset.json";
import marketCrossing from "@/assets/photos/market-crossing.jpg.asset.json";
import nabakalebara from "@/assets/photos/nabakalebara.jpg.asset.json";
import niyamgiriHills from "@/assets/photos/niyamgiri-hills.jpg.asset.json";
import ochreCarriers from "@/assets/photos/ochre-carriers.jpg.asset.json";
import parkGreenDay from "@/assets/photos/park-green-day.jpg.asset.json";
import rebirth from "@/assets/photos/rebirth.jpg.asset.json";
import sculptureArtTrail from "@/assets/photos/sculpture-art-trail.jpg.asset.json";
import sculptureRedForm from "@/assets/photos/sculpture-red-form.jpg.asset.json";
import sculptureRedInstallation from "@/assets/photos/sculpture-red-installation.jpg.asset.json";
import tondoBlueTriangle from "@/assets/photos/tondo-blue-triangle.jpg.asset.json";
import tondoGathering from "@/assets/photos/tondo-gathering.jpg.asset.json";
import tondoJourney from "@/assets/photos/tondo-journey.jpg.asset.json";
import tondoMotherChildren from "@/assets/photos/tondo-mother-children.jpg.asset.json";
import tondoRadiantWoman from "@/assets/photos/tondo-radiant-woman.jpg.asset.json";
import tondoSunflowerPath from "@/assets/photos/tondo-sunflower-path.jpg.asset.json";
import tondoThreeWomen from "@/assets/photos/tondo-three-women.jpg.asset.json";
import tondoTwoSisters from "@/assets/photos/tondo-two-sisters.jpg.asset.json";
import tondoWomanStaff from "@/assets/photos/tondo-woman-staff.jpg.asset.json";
import untitled2015 from "@/assets/photos/untitled-2015.jpg.asset.json";
import vision2040 from "@/assets/photos/vision-2040.jpg.asset.json";
import yellowForest from "@/assets/photos/yellow-forest.jpg.asset.json";
import yellowValley from "@/assets/photos/yellow-valley.jpg.asset.json";
import { assetUrl } from "@/lib/asset-url";

export const photo = {
  portrait: assetUrl(artistPortrait),
  cityMapBlue: assetUrl(cityMapBlue),
  cityRedMarket: assetUrl(cityRedMarket),
  dongariaPortrait: assetUrl(dongariaPortrait),
  groveGathering: assetUrl(groveGathering),
  hillProcession: assetUrl(hillProcession),
  hunger: assetUrl(hunger),
  marketAbundance: assetUrl(marketAbundance),
  marketCrossing: assetUrl(marketCrossing),
  nabakalebara: assetUrl(nabakalebara),
  niyamgiriHills: assetUrl(niyamgiriHills),
  ochreCarriers: assetUrl(ochreCarriers),
  parkGreenDay: assetUrl(parkGreenDay),
  rebirth: assetUrl(rebirth),
  sculptureArtTrail: assetUrl(sculptureArtTrail),
  sculptureRedForm: assetUrl(sculptureRedForm),
  sculptureRedInstallation: assetUrl(sculptureRedInstallation),
  tondoBlueTriangle: assetUrl(tondoBlueTriangle),
  tondoGathering: assetUrl(tondoGathering),
  tondoJourney: assetUrl(tondoJourney),
  tondoMotherChildren: assetUrl(tondoMotherChildren),
  tondoRadiantWoman: assetUrl(tondoRadiantWoman),
  tondoSunflowerPath: assetUrl(tondoSunflowerPath),
  tondoThreeWomen: assetUrl(tondoThreeWomen),
  tondoTwoSisters: assetUrl(tondoTwoSisters),
  tondoWomanStaff: assetUrl(tondoWomanStaff),
  untitled2015: assetUrl(untitled2015),
  vision2040: assetUrl(vision2040),
  yellowForest: assetUrl(yellowForest),
  yellowValley: assetUrl(yellowValley),
} as const;
